<h1 style="background-color:rgb(035,21,133);color:white; padding:20px; border-radius:20px;text-align:center; border:2px; solid: rgb(099,21,133);">
Assignment 04 Tayyaba Sadaqat
</h1>

## Descriptive Statistics

### 1. Quantitative vs Qualitative

- **Quantitative data** are numerical values (e.g., marks, height). 
- **Qualitative data** are categories (e.g., gender, color).

### 2. Mean Median Mode

- Mean is the arithmetic average. 
- Median is the middle value after sorting. Median is preferred when data contains outliers.
- Mode is the most frequent value. 

### 3. Variance & Standard Deviation

- Variance measures spread around the mean. 
- Standard deviation is the square root of variance and is in the original units.

### 4. Z-score

A Z-score shows how many standard deviations a value is from the mean. Values beyond about ±3 are often considered outliers.

## Practical 1
Calculate mean, median and mode manually and using built-in functions.

In [1]:
import statistics as st
marks=[78,85,92,67,74,88,90,81,76,85]
print("Marks:",marks)
manual_mean=sum(marks)/len(marks)
s=sorted(marks)
manual_median=(s[4]+s[5])/2
from collections import Counter
manual_mode=Counter(marks).most_common(1)[0][0]
print(manual_mean,manual_median,manual_mode)
print(st.mean(marks),st.median(marks),st.mode(marks))

Marks: [78, 85, 92, 67, 74, 88, 90, 81, 76, 85]
81.6 83.0 85
81.6 83.0 85


## Practical 2
Variance, standard deviation and coefficient of variation.

In [2]:
import statistics as st
mean=st.mean(marks)
var=st.variance(marks)
std=st.stdev(marks)
cv=(std/mean)*100
print(var,std,cv)

62.044444444444444 7.876829593462363 9.652977442968583


## Practical 3
Z-scores and outlier detection.

In [3]:
zs=[(x-mean)/std for x in marks]
for m,z in zip(marks,zs):
    print(m,round(z,2),"Outlier" if abs(z)>3 else "")

78 -0.46 
85 0.43 
92 1.32 
67 -1.85 
74 -0.96 
88 0.81 
90 1.07 
81 -0.08 
76 -0.71 
85 0.43 


## Practical 4
Correlation coefficient.

In [12]:
import numpy as np
study_hours=np.array([2,3,4,5,6,7,8,4,5,6])
marks_np=np.array(marks)
print(np.corrcoef(study_hours,marks_np)[0,1])

0.21633395952539455


# Section 2: NumPy & Pandas

### Task 1

In [5]:
import numpy as np
a=np.array([1,2,3,4,5,6])
b=np.arange(10)
c=np.random.randint(1,50,6)
print(a)
print(b)
print(c)
print(a.reshape(2,3))
print(a[2],a[1:5])

[1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8 9]
[23  1 42 12 36  1]
[[1 2 3]
 [4 5 6]]
3 [2 3 4 5]


### Task 2

In [6]:
print(np.sqrt(a))
print(np.exp(a))
print(np.max(a),np.min(a))
print(a+5)
print(a*2)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
6 1
[ 6  7  8  9 10 11]
[ 2  4  6  8 10 12]


### Task 3

In [7]:
import pandas as pd
df=pd.DataFrame({"Name":["Ali","Sara","Ahmed","Ayesha","Bilal"],
"Subject":["Math","Math","CS","CS","Math"],
"Marks":[80,90,85,None,70]})
print(df.head())
print(df.shape)
print(df.dtypes)

     Name Subject  Marks
0     Ali    Math   80.0
1    Sara    Math   90.0
2   Ahmed      CS   85.0
3  Ayesha      CS    NaN
4   Bilal    Math   70.0
(5, 3)
Name           str
Subject        str
Marks      float64
dtype: object


### Task 4

In [8]:
print(df[df["Marks"]>75][["Name","Marks"]])

    Name  Marks
0    Ali   80.0
1   Sara   90.0
2  Ahmed   85.0


### Task 5

In [9]:
print(df.isnull().sum())
df["Marks"]=df["Marks"].fillna(df["Marks"].mean())
print(df)

Name       0
Subject    0
Marks      1
dtype: int64
     Name Subject  Marks
0     Ali    Math  80.00
1    Sara    Math  90.00
2   Ahmed      CS  85.00
3  Ayesha      CS  81.25
4   Bilal    Math  70.00


### Task 6

In [10]:
print(df.groupby("Subject")["Marks"].mean())

Subject
CS      83.125
Math    80.000
Name: Marks, dtype: float64


### Task 7

In [11]:
df2=pd.DataFrame({"Name":["Zain","Fatima"],"Subject":["Math","CS"],"Marks":[88,91]})
print(pd.concat([df,df2],ignore_index=True))
print(pd.merge(df,df2,on="Subject",how="inner"))

     Name Subject  Marks
0     Ali    Math  80.00
1    Sara    Math  90.00
2   Ahmed      CS  85.00
3  Ayesha      CS  81.25
4   Bilal    Math  70.00
5    Zain    Math  88.00
6  Fatima      CS  91.00
   Name_x Subject  Marks_x  Name_y  Marks_y
0     Ali    Math    80.00    Zain       88
1    Sara    Math    90.00    Zain       88
2   Ahmed      CS    85.00  Fatima       91
3  Ayesha      CS    81.25  Fatima       91
4   Bilal    Math    70.00    Zain       88
